# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "robotxt"
version = "0.1.0"
edition = "2021"

license = "MIT"
readme = "./README.md"
description = """
The implementation of the robots.txt protocol with
the extensions support.
"""

authors = ["Oleh Martsokha <o.martsokha@gmail.com>"]
repository = "https://github.com/xwde/countio"
homepage = "https://github.com/xwde/countio"
categories = ["parser-implementations", "parsing", "web-programming"]
keywords = ["robots", "crawler", "parser"]

[package.metadata.docs.rs]
all-features = true

[lib]
path = "./lib.rs"

[features]
default = []
time = ["dep:time"]

[dependencies]
regex = { version = "1.7.1" }
url = { version = "2.3.1" }
time = { version = "0.3.20", optional = true }
